-- An arbitrary table representing section CSE16
-- A section holds the information about student ID, name, address and contact number
CREATE TABLE CSE16(
    SID NUMBER,
    NAME VARCHAR2(25),
    ADDRESS VARCHAR2(30),
    CONTACT_NUMBER VARCHAR2(14),
    CONSTRAINT PK_CSE16 PRIMARY KEY (SID)
);

-- An arbitrary table representing class CSE9406
-- Each class table can represent one specific subject class taken by a teacher
-- Holds student ID and DAY representing each academic day where class has been taken and students were present
-- It is an arbitrary linking table
CREATE TABLE CSE9406(
    SID NUMBER,
    DAY VARCHAR2(6),
    CONSTRAINT PK_CSE9406 PRIMARY KEY (SID, DAY),
    CONSTRAINT FK_CSE9406 FOREIGN KEY (SID) REFERENCES CSE16 (SID)
);

-- Arbitrary value insertion into CSE16 for test purpose
INSERT INTO CSE16 VALUES (101, 'Ahmad Omar Ahsan', 'Paribag', '12311156');
INSERT INTO CSE16 VALUES (102, 'Shafkat Rahman Farabi', 'Dhaka', '12398725');
INSERT INTO CSE16 VALUES (103, 'Mashrur Nazrul Mashfi', 'Dhaka', '12456876');
INSERT INTO CSE16 VALUES (104, 'Mohammad Sabik Irbaz', 'Coxs Bazar', '12786861');
INSERT INTO CSE16 VALUES (105, 'Gazi Wasif Akram', 'Dhaka', '12300583');
INSERT INTO CSE16 VALUES (106, 'Muhammed Barry', 'Gambia', '92245671');
INSERT INTO CSE16 VALUES (107, 'Mahruf Islam Prottoy', 'Dhaka', '12342992');
INSERT INTO CSE16 VALUES (108, 'Nahian Muhtasim Zahin', 'Dhaka', '12456979');

-- Arbitrary value insertion into CSE9406 for test purpose
INSERT INTO CSE9406 VALUES (101, 'OCT01');
INSERT INTO CSE9406 VALUES (102, 'OCT01');
INSERT INTO CSE9406 VALUES (103, 'OCT01');
INSERT INTO CSE9406 VALUES (104, 'OCT01');
INSERT INTO CSE9406 VALUES (105, 'OCT01');
INSERT INTO CSE9406 VALUES (106, 'OCT01');
INSERT INTO CSE9406 VALUES (107, 'OCT01');
INSERT INTO CSE9406 VALUES (108, 'OCT01');
INSERT INTO CSE9406 VALUES (102, 'OCT02');
INSERT INTO CSE9406 VALUES (104, 'OCT02');
INSERT INTO CSE9406 VALUES (105, 'OCT02');
INSERT INTO CSE9406 VALUES (107, 'OCT02');
INSERT INTO CSE9406 VALUES (108, 'OCT02');
INSERT INTO CSE9406 VALUES (101, 'OCT03');
INSERT INTO CSE9406 VALUES (103, 'OCT03');
INSERT INTO CSE9406 VALUES (104, 'OCT03');
INSERT INTO CSE9406 VALUES (105, 'OCT03');
INSERT INTO CSE9406 VALUES (106, 'OCT03');
INSERT INTO CSE9406 VALUES (107, 'OCT03');
INSERT INTO CSE9406 VALUES (101, 'OCT04');
INSERT INTO CSE9406 VALUES (102, 'OCT04');
INSERT INTO CSE9406 VALUES (103, 'OCT04');




-- A View:CSE16_STUDENT_COUNT returning total student count of section
CREATE OR REPLACE VIEW CSE16_STUDENT_COUNT AS
SELECT COUNT(SID) STUDENT_COUNT FROM CSE16;
-- SELECT * FROM CSE16_STUDENT_COUNT;

-- A View:CSE9406_ATTENDANCE_COUNT returning attendance count for every student based on student ID
CREATE OR REPLACE VIEW CSE9406_ATTENDANCE_COUNT AS
SELECT CLASS.SID, COUNT(CLASS.DAY) ATTENDANCE_COUNT
FROM CSE9406 CLASS
GROUP BY CLASS.SID;
-- SELECT * FROM CSE9406_ATTENDANCE_COUNT;

-- A View:CSE9406_TOTAL_CLASS_COUNT returning total academic days of class
CREATE OR REPLACE VIEW CSE9406_TOTAL_CLASS_COUNT AS
SELECT COUNT(UNIQUE DAY) TOTAL_CLASS_COUNT
FROM CSE9406;
-- SELECT * FROM CSE9406_TOTAL_CLASS_COUNT;

-- A View:CSE9406_PERCENTAGE returning attendance percentage for every student based on student ID
CREATE OR REPLACE VIEW CSE9406_PERCENTAGE AS
SELECT ATTENDANCE.SID, (ATTENDANCE.ATTENDANCE_COUNT / (SELECT TOTAL_CLASS_COUNT FROM CSE9406_TOTAL_CLASS_COUNT)) * 100 ATTENDANCE_PERCENTAGE
FROM CSE9406_ATTENDANCE_COUNT ATTENDANCE;
--SELECT * FROM CSE9406_PERCENTAGE;

-- A View:CSE9406_DEFAULTERS returning the student IDs and attendance percentage for those students who has attendance below 75%
CREATE OR REPLACE VIEW CSE9406_DEFAULTERS AS
SELECT * FROM CSE9406_PERCENTAGE
WHERE ATTENDANCE_PERCENTAGE < 75
ORDER BY SID ASC;
--SELECT * FROM CSE9406_DEFAULTERS;

-- A View:CSE9406_DEFAULTERS_COUNT returning total defaulter count of the class
CREATE OR REPLACE VIEW CSE9406_DEFAULTERS_COUNT AS
SELECT COUNT(SID) DEFAULTER_COUNT
FROM CSE9406_DEFAULTERS;
--SELECT * FROM CSE9406_DEFAULTERS_COUNT;

-- A View:CSE9406_PERCENTAGE_W_NAME returning attendance percentage for every student based on student ID with name
CREATE OR REPLACE VIEW CSE9406_PERCENTAGE_W_NAME AS
SELECT DEFAULTERS.SID, SECTION.NAME, DEFAULTERS.ATTENDANCE_PERCENTAGE
FROM CSE16 SECTION, CSE9406_PERCENTAGE DEFAULTERS
WHERE DEFAULTERS.SID = SECTION.SID
ORDER BY DEFAULTERS.SID ASC;
--SELECT * FROM CSE9406_PERCENTAGE_W_NAME;

-- A View:CSE9406_DEFAULTERS_W_NAME returning the student IDs, names and attendance percentage for those students who has attendance below 75%
CREATE OR REPLACE VIEW CSE9406_DEFAULTERS_W_NAME AS
SELECT DEFAULTERS.SID, SECTION.NAME, DEFAULTERS.ATTENDANCE_PERCENTAGE
FROM CSE16 SECTION, CSE9406_DEFAULTERS DEFAULTERS
WHERE DEFAULTERS.SID = SECTION.SID
ORDER BY DEFAULTERS.SID ASC;
--SELECT * FROM CSE9406_DEFAULTERS_W_NAME;

-- A View:CSE9406_EXTENDED_ATTENDANCE returning the student ID, name, address, contact number, attendance count and attendance percentage for all students of the section
CREATE OR REPLACE VIEW CSE9406_EXTENDED_ATTENDANCE AS
SELECT SECTION.SID, SECTION.NAME, SECTION.ADDRESS, SECTION.CONTACT_NUMBER, ACOUNT.ATTENDANCE_COUNT, APERCENTAGE.ATTENDANCE_PERCENTAGE
FROM CSE16 SECTION, CSE9406_ATTENDANCE_COUNT ACOUNT, CSE9406_PERCENTAGE APERCENTAGE
WHERE SECTION.SID = ACOUNT.SID AND SECTION.SID = APERCENTAGE.SID
ORDER BY SECTION.SID ASC;
--SELECT * FROM CSE9406_EXTENDED_ATTENDANCE;

-- A View:CSE9406_TAKENDAYS returning the days when classes have been taken
CREATE OR REPLACE VIEW CSE9406_TAKENDAYS AS 
SELECT UNIQUE DAY FROM CSE9406;
--SELECT * FROM CSE9406_TAKENDAYS;

/*
SELECT * FROM CSE9406
WHERE DAY = 'SEP24';*/

/*
DELETE FROM CSE9406
WHERE SID = 101 AND DAY = 'SEP25';*/